#!/bin/bash
eval "$($HOME/mc3/bin/conda 'shell.bash' 'hook')"
conda activate WidthAndSharpness
pip install -r requirements.txt

EXP_NUMS_LIST=($(seq 1 28))
EXP_FILES=""
EXP_SUBDIR="exp755"
for i in "${EXP_NUMS_LIST[@]}"; do
    string+="experiment_results/${EXP_SUBDIR}/exp${i}/exp${i}.json,"
done
EXP_FILES=${string%,}
python VizInitialExperiment.py ${EXP_FILES} --only feature

conda deactivate