#!/bin/bash
eval "$($HOME/mc3/bin/conda 'shell.bash' 'hook')"
conda activate WidthAndSharpness
pip install -r requirements.txt

python InitialExperiment.py experiment_results/exp13.json
python VizInitialExperiment.py experiment_results/exp13.json

conda deactivate