#!/bin/bash
eval "$($HOME/mc3/bin/conda 'shell.bash' 'hook')"
conda activate WidthAndSharpness
pip install -r requirements.txt

python InitialExperiment.py
python VizInitialExperiment.py experiment_results/exp1.pkl

conda deactivate